version: '3'

services:

  app:
    container_name: cmpt-2500-project-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./predictions:/app/predictions
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - mlflow-network

  mlflow:
    container_name: cmpt-2500-project-mlflow
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow
    networks:
      - mlflow-network

# 🔥 FIX: Move these to top-level (NOT under 'services') 🔥
networks:
  mlflow-network:
    driver: bridge

volumes:
  mlflow-data:
    driver: local
