version: '3'

services:

  app:
    container_name: cmpt-2500-project-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./predictions:/app/predictions
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
      - prometheus
    networks:
      - ml-network

  mlflow:
    container_name: cmpt-2500-project-mlflow
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow
    networks:
      - ml-network

  prometheus:
    image: prom/prometheus:latest
    container_name: cmpt-2500-project-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/rules:/etc/prometheus/rules  # ✅ Added alert rules directory
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - ml-network

  grafana:
    image: grafana/grafana:latest
    container_name: cmpt-2500-project-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge

volumes:
  mlflow-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
