version: '3.8'

services:
  app:
    container_name: cmpt-2500-project-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./predictions:/app/predictions
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    depends_on:
      - mlflow
    networks:
      - ml-network

  mlflow:
    container_name: cmpt-2500-project-mlflow
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/artifacts
      - ./mlflow.db:/mlflow/mlflow.db
      - ./logs:/mlflow/logs
    networks:
      - ml-network

  train-metrics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmpt-2500-project-train
    command: python src/train.py
    depends_on:
      - mlflow
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
      - ./mlruns:/mlflow/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - ml-network

volumes:
  mlflow-data:
    driver: local

networks:
  ml-network:
    driver: bridge
