global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'ml-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['cmpt-2500-project-app:8002']  # ✅ Correct container name
    metrics_path: /metrics
    scheme: http

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'model-training'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'cmpt-2500-project-train:8002'  # ✅ Also updated here
    metrics_path: /metrics
    scheme: http
    scrape_timeout: 3s
