groups:
  - name: prediction-api-alerts
    rules:
      - alert: HighMemoryUsage
        expr: app_memory_usage_bytes > 1500000000  # 1.5 GB
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage"
          description: "Memory usage exceeded 1.5GB for over 2 minutes."

      - alert: HighCPUUsage
        expr: app_cpu_usage_percent > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage over 80% for 2 minutes."

      - alert: HighErrorRate
        expr: rate(model_prediction_requests_total{status="error"}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Prediction errors exceed 5%"
          description: "More than 5% of prediction API responses are errors."

  - name: model-training-alerts
    rules:
      - alert: LowRSquared
        expr: regression_r_squared < 0.6
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low R² Score Detected"
          description: "Model's R-squared value is below 0.6 for 5 minutes."

      - alert: HighMSE
        expr: regression_mean_squared_error > 500
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High Mean Squared Error"
          description: "Model's MSE exceeded 500 during training."
